### ISSUE TITLE
Mac operating problems

### ISSUE THREAD

**Issue by linkangren** [microsoft/Bringing-Old-Photos-Back-to-Life#108]
MAC Run scratch photo

initializing the dataloader
model weights loaded
Traceback (most recent call last):
  File "detection.py", line 155, in <module>
    main(config)
  File "detection.py", line 80, in main
    model.to(config.GPU)
  File "/Users/linkangren/opt/anaconda3/envs/paddle_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 416, in to
    device, dtype, non_blocking = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Device index must not be negative
You are using NL + Res
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    input_loader = os.listdir(opt.test_input)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/linkangren/Desktop/B/output/stage_1_restore_output/masks/input'
Finish Stage 1 ...

Running Stage 2: Face Detection
Finish Stage 2 ...

Running Stage 3: Face Enhancement
dataset [FaceTestDataset] of size 0 was created
The size of the latent vector size is [8,8]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
hi :)
Finish Stage 3 ...

Running Stage 4: Blending
Finish Stage 4 ...

**Comment by linkangren** [comment]
File "detection.py", line 13, in <module>
    from detection_models import networks
  File "/Users/linkangren/Desktop/B/Global/detection_models/networks.py", line 7, in <module>
    from detection_models.sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'detection_models.sync_batchnorm'
You are using NL + Res
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    input_loader = os.listdir(opt.test_input)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/linkangren/Desktop/B/output/stage_1_restore_output/masks/input'
Finish Stage 1 ...


Running Stage 2: Face Detection
Finish Stage 2 ...


Running Stage 3: Face Enhancement
Traceback (most recent call last):
  File "test_face.py", line 9, in <module>
    from models.pix2pix_model import Pix2PixModel
  File "/Users/linkangren/Desktop/B/Face_Enhancement/models/pix2pix_model.py", line 5, in <module>
    import models.networks as networks
  File "/Users/linkangren/Desktop/B/Face_Enhancement/models/networks/__init__.py", line 6, in <module>
    from models.networks.generator import *
  File "/Users/linkangren/Desktop/B/Face_Enhancement/models/networks/generator.py", line 8, in <module>
    from models.networks.normalization import get_nonspade_norm_layer
  File "/Users/linkangren/Desktop/B/Face_Enhancement/models/networks/normalization.py", line 8, in <module>
    from models.networks.sync_batchnorm import SynchronizedBatchNorm2d
ModuleNotFoundError: No module named 'models.networks.sync_batchnorm'

**Comment by zhangmozhe** [comment]
Have you tried our colab demo?
