### ISSUE TITLE
No such file or directory:  '\stage_1_restore_output\\restored_image'

### ISSUE THREAD

**Issue by ZevFung** [microsoft/Bringing-Old-Photos-Back-to-Life#126]
PS F:\fzw_work\projiect_OtherProject\python\Bringing-Old-Photos-Back-to-Life> python run.py --input_folder F:\11\1 --output_folder F:\11\2 --GPU 0
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    opt = TestOptions().parse(save=False)
  File "F:\fzw_work\projiect_OtherProject\python\Bringing-Old-Photos-Back-to-Life\Global\options\base_options.py", line 350, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "C:\Users\xiaomingming\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\cuda\__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
Traceback (most recent call last):
  File "run.py", line 95, in <module>
    for x in os.listdir(stage_1_results):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'F:\\11\\2\\stage_1_restore_output\\restored_image'

**Comment by ZevFung** [comment]
Install Python CUDA and cudnn
