### ISSUE TITLE
[enforce fail at ..\c10\core\CPUAllocator.cpp:75] data. DefaultCPUAllocator: not enough memory: you tried to allocate 39210336256 bytes. Buy new RAM!  

### ISSUE THREAD

**Issue by bwxz** [microsoft/Bringing-Old-Photos-Back-to-Life#128]
**some step has problem log as :**
 

 $ python run.py --input_folder "test/old/My/" --output_folder "test/out" --GPU -1 --with_scratch
initializing the dataloader
model weights loaded
directory of testing image: G:\Learning_Files\Python\OldPicture_2_New\Bringing-Old-Photos-Back-to-Life-master\test\old\My
processing 2.jpg
You are using NL + Res
Now you are processing 2.png
Skip 2.png due to an error:
[enforce fail at ..\c10\core\CPUAllocator.cpp:75] data. DefaultCPUAllocator: not enough memory: you tried to allocate 39210336256 bytes. Buy new RAM!
Traceback (most recent call last):
  File "detect_all_dlib.py", line 6, in <module>
    import skimage.io as io
  File "E:\Program Files\Python36\lib\site-packages\skimage\__init__.py", line 125, in <module>
    from .util.dtype import (img_as_float32,
  File "E:\Program Files\Python36\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "E:\Program Files\Python36\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
  File "__init__.pxd", line 918, in init skimage.util._remap
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
E:\Program Files\Python36\lib\site-packages\scipy\__init__.py:147: UserWarning: NumPy 1.14.5 or above is required for this version of SciPy (detected version 1.13.3)
  UserWarning)
dataset [FaceTestDataset] of size 0 was created
The size of the latent vector size is [8,8]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
hi :)
Traceback (most recent call last):
  File "align_warp_back_multiple_dlib.py", line 6, in <module>
    import skimage.io as io
  File "E:\Program Files\Python36\lib\site-packages\skimage\__init__.py", line 125, in <module>
    from .util.dtype import (img_as_float32,
  File "E:\Program Files\Python36\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "E:\Program Files\Python36\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
  File "__init__.pxd", line 918, in init skimage.util._remap
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
Running Stage 1: Overall restoration
Finish Stage 1 ...

Running Stage 2: Face Detection
Finish Stage 2 ...

Running Stage 3: Face Enhancement
Finish Stage 3 ...

Running Stage 4: Blending
Finish Stage 4 ...

All the processing is done. Please check the results.

**Comment by zhangmozhe** [comment]
Hi, we are currently developing algorithm to fit for large images. Now you try to resize the input photo a little bit and have a try. Or you can use Colab demo which provides larger GPU memory. Thanks.

**Comment by bwxz** [comment]
> Hi, we are currently developing algorithm to fit for large images. Now you try to resize the input photo a little bit and have a try. Or you can use Colab demo which provides larger GPU memory. Thanks.

OK,,thanks and learn a lot
