### ISSUE TITLE
Face Enhancement Erroring Out

### ISSUE THREAD

**Issue by mahesh557** [microsoft/Bringing-Old-Photos-Back-to-Life#138]
Hi,

I am seeing below error in face enhancement, can you help to fix

```
Running Stage 3: Face Enhancement
Traceback (most recent call last):
  File "D:\photo_restoration\Face_Enhancement\test_face.py", line 15, in <module>
    opt = TestOptions().parse()
  File "D:\photo_restoration\Face_Enhancement\options\base_options.py", line 262, in parse
    opt = self.gather_options()
  File "D:\photo_restoration\Face_Enhancement\options\base_options.py", line 197, in gather_options
    parser = model_option_setter(parser, self.isTrain)
  File "D:\photo_restoration\Face_Enhancement\models\pix2pix_model.py", line 12, in modify_commandline_options
    networks.modify_commandline_options(parser, is_train)
AttributeError: module 'models.networks' has no attribute 'modify_commandline_options'
Finish Stage 3 ...
```

**Comment by mahesh557** [comment]
Found the error, below instruction is over riding __init__.py from sync_batchnorm to networks while copying.
Restored the network/__init__.py from the git, then it worked out fine.

```
cd Face_Enhancement/models/networks/
git clone https://github.com/vacancy/Synchronized-BatchNorm-PyTorch
cp -rf Synchronized-BatchNorm-PyTorch/sync_batchnorm .
cd ../../../
```
