### ISSUE TITLE
Can you release the training log ?

### ISSUE THREAD

**Issue by maryhh** [microsoft/Bringing-Old-Photos-Back-to-Life#164]
Can you release the training log (the loss log ),so i can track the training process.

**Comment by MengXinChengXuYuan** [comment]
I'm also looking forward to the training log
In my experiment, using the defaut model setting and my own dataset
When training model A, 'G_featD' is very high around 1.5~1.7 and 'featD_real' 'featD_fake' are very low around 0.08~0.12
When traning model Mapping, even though I used g_lr = x, d_lr = 0.6x, 'G_GAN' will be around 1.7-2.0, and 'D_real' 'D_fake' around 0.03~0.06

I think this means the gan training procedure was already collapsed, which leads chessboard effect

Could you please release the traning log, that we can figure out the how those losses varies when everything goes well?

**Comment by syfbme** [comment]
Hi @MengXinChengXuYuan 
What's your --k_size value?

**Comment by MengXinChengXuYuan** [comment]
> Hi @MengXinChengXuYuan
> What's your --k_size value?

I redesign the network, for the efficiency.
Most conv kernels are have 3*3, transposeConvs are 4 * 4.
I don't think this will have a lot effect

**Comment by syfbme** [comment]
> I'm also looking forward to the training log
> In my experiment, using the defaut model setting and my own dataset
> When training model A, G_featD is very high around 1.5-1.7 and featD_real featD_fake are very low around 0.08-0.12
> When traning model Mapping, even though I used g_lr = x, d_lr = 0.6x, G_GAN will be around 1.7-2.0, and D_real D_fake around 0.03~0.06
> 
> I think this means the gan training procedure was already collapsed, which leads chessboard effect
> 
> Could you please release the traning log, that we can figure out the how those losses varies when everything goes well? @raywzy

Maybe you can try to replace deconv with upsample+conv to get rid of chessboard effect

**Comment by MengXinChengXuYuan** [comment]
> > I'm also looking forward to the training log
> > In my experiment, using the defaut model setting and my own dataset
> > When training model A, G_featD is very high around 1.5-1.7 and featD_real featD_fake are very low around 0.08-0.12
> > When traning model Mapping, even though I used g_lr = x, d_lr = 0.6x, G_GAN will be around 1.7-2.0, and D_real D_fake around 0.03~0.06
> > I think this means the gan training procedure was already collapsed, which leads chessboard effect
> > Could you please release the traning log, that we can figure out the how those losses varies when everything goes well? @raywzy
> 
> Maybe you can try to replace deconv with upsample+conv to get rid of chessboard effect

Thanks a lot for the advice!
I tried, following https://distill.pub/2016/deconv-checkerboard/
But no matter using upsample+conv or ZOH, there are always other problms :(
When the computational comlexity of G is low, this will get even worse

**Comment by syfbme** [comment]
Hi @MengXinChengXuYuan 
What do you mean by "there are always other problems".
There is no chessboard effects but other issue? If so, what is that?

**Comment by Mr-doraemon** [comment]
Hi， @MengXinChengXuYuan 
May I ask what range your G_Feat_L2 loss maintains when training the mapping model?

**Comment by Ssakura-go** [comment]
> > > I'm also looking forward to the training log
> > > In my experiment, using the defaut model setting and my own dataset
> > > When training model A, G_featD is very high around 1.5-1.7 and featD_real featD_fake are very low around 0.08-0.12
> > > When traning model Mapping, even though I used g_lr = x, d_lr = 0.6x, G_GAN will be around 1.7-2.0, and D_real D_fake around 0.03~0.06
> > > I think this means the gan training procedure was already collapsed, which leads chessboard effect
> > > Could you please release the traning log, that we can figure out the how those losses varies when everything goes well? @raywzy
> > 
> > 
> > Maybe you can try to replace deconv with upsample+conv to get rid of chessboard effect
> 
> Thanks a lot for the advice! I tried, following https://distill.pub/2016/deconv-checkerboard/ But no matter using upsample+conv or ZOH, there are always other problms :( When the computational comlexity of G is low, this will get even worse

Dear, did you solve the problem(chessboard effect) at last?

**Comment by CodeMadUser** [comment]
> 

Sorry to interrupt, but did you complete your training successfully? I had this problem when I retrained VAE_A, did you encounter it? Is this a version problem? Thank you.
checkpoints\restoration\VAE_A_quality\domainA_SR_old_photos\latest_net_G.pth not exists yet!
---------- G Networks reloaded -------------
checkpoints\restoration\VAE_A_quality\domainA_SR_old_photos\latest_net_D.pth not exists yet!
checkpoints\restoration\VAE_A_quality\domainA_SR_old_photos\latest_net_feat_D.pth not exists yet!
---------- D Networks reloaded -------------
---------- Optimizers initialized -------------
checkpoints\restoration\VAE_A_quality\domainA_SR_old_photos\latest_optimizer_D.pth not exists yet!
checkpoints\restoration\VAE_A_quality\domainA_SR_old_photos\latest_optimizer_G.pth not exists yet!
checkpoints\restoration\VAE_A_quality\domainA_SR_old_photos\latest_optimizer_featD.pth not exists yet!
---------- Optimizers reloaded -------------
---------- Current LR is 0.00020000 -------------
Traceback (most recent call last):
  File "train_domain_A.py", line 47, in <module>
    fd.write(str(model.module.netG))
  File "D:\pythonProject\5_19\BringOldBack\venv\lib\site-packages\torch\nn\modules\module.py", line 594, in __getattr__       
    type(self).__name__, name))
AttributeError: 'Pix2PixHDModel' object has no attribute 'module'
