### ISSUE TITLE
ImportError: No module named detection_util.util

### ISSUE THREAD

**Issue by ken-wawa** [microsoft/Bringing-Old-Photos-Back-to-Life#165]
Hi,

After installation (which was quite tricky but somehow I finally did it), when running run.py (with --GPU -1 as i don't have nvidia card) I'm getting the following error:

Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "detection.py", line 18, in <module>
    from detection_util.util import *
ImportError: No module named detection_util.util
You are using NL + Res
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    input_loader = os.listdir(opt.test_input)
OSError: [Errno 2] No such file or directory: '/media/piotr/DANE/FOTO/zdjecia_albumik_rodzinny1_tmp_output/stage_1_restore_output/masks/input'
Finish Stage 1 ...

Running Stage 2: Face Detection
Traceback (most recent call last):
  File "detect_all_dlib.py", line 144, in <module>
    os.makedirs(url, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
Finish Stage 2 ...

Running Stage 3: Face Enhancement
Traceback (most recent call last):
  File "test_face.py", line 9, in <module>
    from models.pix2pix_model import Pix2PixModel
  File "/media/piotr/DANE/foto.microsoft_ai_enhancement/Bringing-Old-Photos-Back-to-Life-master/Face_Enhancement/models/pix2pix_model.py", line 5, in <module>
    import models.networks as networks
  File "/media/piotr/DANE/foto.microsoft_ai_enhancement/Bringing-Old-Photos-Back-to-Life-master/Face_Enhancement/models/networks/__init__.py", line 6, in <module>
    from models.networks.generator import *
  File "/media/piotr/DANE/foto.microsoft_ai_enhancement/Bringing-Old-Photos-Back-to-Life-master/Face_Enhancement/models/networks/generator.py", line 8, in <module>
    from models.networks.normalization import get_nonspade_norm_layer
  File "/media/piotr/DANE/foto.microsoft_ai_enhancement/Bringing-Old-Photos-Back-to-Life-master/Face_Enhancement/models/networks/normalization.py", line 21
    nonlocal norm_type
                     ^
SyntaxError: invalid syntax
Finish Stage 3 ...

Running Stage 4: Blending
Finish Stage 4 ...

All the processing is done. Please check the results.

And there is no any result. Any ideas how to solve that?

**Comment by zhangmozhe** [comment]
Hello, have you solve the problem?
