### ISSUE TITLE
how does it run witn option --GPU -1

### ISSUE THREAD

**Issue by wenbuliaoyi** [microsoft/Bringing-Old-Photos-Back-to-Life#211]
Hello!
i run this option on M1 macbook, but it shows: "Torch not compiled with CUDA enabled"
how can i fix this problem
thanks

**Comment by davaram** [comment]
You need to install the torch gpu version, apt installs the CPU version by default, so GPU is not used

**Comment by MerzCheung** [comment]
torch==1.5.1+cu92
torchvision==0.6.1+cu92
Error:
 python run.py --input_folder D:\\learn_project\\Bringing-Old-Photos-Back-to-Life\\test_images\\old_w_scratch --output_folder D:\\learn_project\\Bringing-Old-Photos-Back-to-Life\\output --GPU 1  --with_scratch
detection.py:25: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  def data_transforms(img, full_size, method=Image.BICUBIC):
initializing the dataloader
model weights loaded
Traceback (most recent call last):
  File "detection.py", line 178, in <module>
    main(config)
  File "detection.py", line 97, in main
    model.to(config.GPU)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 443, in to
    return self._apply(convert)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 203, in _apply
    module._apply(fn)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 203, in _apply
    module._apply(fn)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 225, in _apply
    param_applied = fn(param)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 441, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
THCudaCheck FAIL file=..\torch\csrc\cuda\Module.cpp line=59 error=10 : invalid device ordinal
test.py:18: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  def data_transforms(img, method=Image.BILINEAR, scale=False):
Traceback (most recent call last):
  File "test.py", line 97, in <module>
    opt = TestOptions().parse(save=False)
  File "D:\learn_project\Bringing-Old-Photos-Back-to-Life\Global\options\base_options.py", line 354, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 245, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at ..\torch\csrc\cuda\Module.cpp:59
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "run.py", line 105, in <module>
    for x in os.listdir(stage_1_results):
FileNotFoundError: [WinError 3] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒·▒▒▒▒: 'D:\\learn_project\\Bringing-Old-Photos-Back-to-Life\\output\\stage_1_restore_output\\restored_image'

thanks
