### ISSUE TITLE
Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by FahaoTang** [microsoft/Bringing-Old-Photos-Back-to-Life#214]
When I run this library on Windows 10, it throws out the following error:

Running Stage 4: Blending
Traceback (most recent call last):
  File "align_warp_back_multiple_dlib.py", line 428, in <module>
    blended = blur_blending_cv2(warped_back, blended, backward_mask)
  File "align_warp_back_multiple_dlib.py", line 219, in blur_blending_cv2
    mask *= 255.0
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
Finish Stage 4 ...

Environment details:

- System: Windows 10
- Python: 3.8 (via Anaconda)
- PyTorch installed with this command: conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
- Numpy version: 
```
conda list numpy
# packages in environment at D:\conda\envs\py38:
#
# Name                    Version                   Build  Channel
numpy                     1.21.2           py38hfca59bb_0
numpy-base                1.21.2           py38h0829f74_0
```

**Comment by ruanqizhen** [comment]
I got the same error

**Comment by ruanqizhen** [comment]
requested a fix:  https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/pull/217

**Comment by sdahyk** [comment]
Edit file "align_warp_back_multiple_dlib.py", line 219, change from 
mask *= 255.0 to mask = (mask\*255.0)

this will solve the problem.

**Comment by stus3y** [comment]
> Edit file "align_warp_back_multiple_dlib.py", line 219, change from mask *= 255.0 to mask = (mask*255.0)
> 
> this will solve the problem.

It works. Thank you.

**Comment by eisraeli** [comment]
@sdahyk You are awesome! Thank you !
