### ISSUE TITLE
module 'models.networks' has no attribute 'modify_commandline_options'

### ISSUE THREAD

**Issue by bill1969** [microsoft/Bringing-Old-Photos-Back-to-Life#225]
Running Stage 3: Face Enhancement
Traceback (most recent call last):
  File "test_face.py", line 15, in <module>
    opt = TestOptions().parse()
  File "E:\picture_fix\Bringing-Old-Photos-Back-to-Life\Face_Enhancement\options\base_options.py", line 262, in parse
    opt = self.gather_options()
  File "E:\picture_fix\Bringing-Old-Photos-Back-to-Life\Face_Enhancement\options\base_options.py", line 197, in gather_options
    parser = model_option_setter(parser, self.isTrain)
  File "E:\picture_fix\Bringing-Old-Photos-Back-to-Life\Face_Enhancement\models\pix2pix_model.py", line 12, in modify_commandline_options
    networks.modify_commandline_options(parser, is_train)
AttributeError: module 'models.networks' has no attribute 'modify_commandline_options'
Finish Stage 3 ...

**Comment by WillianSalceda** [comment]
had the same problem following _Installation_ guide

**Comment by FlowDownTheRiver** [comment]
The solution is I give you the folder structure,you need to have "sync_batchnorm" folder inside
"Bringing-Old-Photos-Back-to-Life\Face_Enhancement\models\networks" folder
so the final structure is going to be like in the picture.Make sure you don't overwrite any file.
![2022-04-26 03_00_24-Window](https://user-images.githubusercontent.com/71787427/165193372-1ca8653a-e0b7-4a7b-9607-3d6381226173.jpg)

I tell you what guys?
After stage 1 it is not worth to do the rest of the stages.Because it is using dlib for faces and even if you compile it with
cuda to run faster,it takes time to process the faces.What is worst is that the final results is not worth the time and processing power spent on it.

So I suggest you to edit the run.py file and comment out stage 2,3,4 for efficiency.

These are the original files : 

![6029756](https://user-images.githubusercontent.com/71787427/165193952-5aa7eebe-bf49-44f0-b868-eecdf505e260.jpg)
![Damaged-Photo-Restoration-before](https://user-images.githubusercontent.com/71787427/165193955-dc0bdf59-4ab6-42bb-81bc-bb7a493318c1.jpg)

These 2 are without face enhancement : 

![6029756](https://user-images.githubusercontent.com/71787427/165193797-493eb41a-5a22-411d-bad9-db874d56bebc.jpg)
![Damaged-Photo-Restoration-before](https://user-images.githubusercontent.com/71787427/165193801-e87faf95-4f69-4fb5-b52d-2017ee7ab686.jpg)

These 2 are with face enhancement : 

![6029756](https://user-images.githubusercontent.com/71787427/165193866-92c02e64-7c90-4c24-8a8c-b0b52489275b.jpg)
![Damaged-Photo-Restoration-before](https://user-images.githubusercontent.com/71787427/165193870-568abf75-a94a-41b2-baf1-8fad02043c68.jpg)
