### ISSUE TITLE
Traing the mapping with scratches

### ISSUE THREAD

**Issue by Estherisok666** [microsoft/Bringing-Old-Photos-Back-to-Life#228]
When I perform"python train_mapping.py --no_TTUR --NL_res --random_hole --use_SN --correlation_renormalize --training_dataset mapping --NL_use_mask --NL_fusion_method combine --non_local Setting_42 --use_v2_degradation --use_vae_which_epoch 200 --continue_train --name mapping_scratch --label_nc 0 --loadSize 256 --fineSize 256 --dataroot [your_data_folder] --no_instance --resize_or_crop crop_only --batchSize 36 --no_html --gpu_ids 0,1,2,3 --nThreads 8 --load_pretrainA [ckpt_of_domainA_SR_old_photos] --load_pretrainB [ckpt_of_domainB_old_photos] --l2_feat 60 --n_downsample_global 3 --mc 64 --k_size 4 --start_r 1 --mapping_n_block 6 --map_mc 512 --use_l1_feat --niter 150 --niter_decay 100 --outputs_dir [your_output_folder] --checkpoints_dir [your_ckpt_folder] --irregular_mask [absolute_path_of_mask_file]"

When I add the parameter'--irregular_mask' ,There was an error  (UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 11: invalid start byte
(my absolute path of mask file is  ./mask/a.png )
and then  there was another error: struct.error: unpack requires a buffer of 4 bytes

**Comment by CodeMadUser** [comment]
> When I perform"python train_mapping.py --no_TTUR --NL_res --random_hole --use_SN --correlation_renormalize --training_dataset mapping --NL_use_mask --NL_fusion_method combine --non_local Setting_42 --use_v2_degradation --use_vae_which_epoch 200 --continue_train --name mapping_scratch --label_nc 0 --loadSize 256 --fineSize 256 --dataroot [your_data_folder] --no_instance --resize_or_crop crop_only --batchSize 36 --no_html --gpu_ids 0,1,2,3 --nThreads 8 --load_pretrainA [ckpt_of_domainA_SR_old_photos] --load_pretrainB [ckpt_of_domainB_old_photos] --l2_feat 60 --n_downsample_global 3 --mc 64 --k_size 4 --start_r 1 --mapping_n_block 6 --map_mc 512 --use_l1_feat --niter 150 --niter_decay 100 --outputs_dir [your_output_folder] --checkpoints_dir [your_ckpt_folder] --irregular_mask [absolute_path_of_mask_file]"
> 
> When I add the parameter'--irregular_mask' ,There was an error (UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 11: invalid start byte (my absolute path of mask file is ./mask/a.png ) and then there was another error: struct.error: unpack requires a buffer of 4 bytes

hello,I am a developer working on image reconstruction. when I run train_domain_B.py,it occurs error:
    Traceback (most recent call last):
    File "train_domain_B.py", line 48, in
    model = create_model(opt)
    File "D:\pythonProject\6_18\BringOldBack\Global\models\models.py", line 17, in create_model
    model.initialize(opt)
    File "D:\pythonProject\6_18\BringOldBack\Global\models\pix2pixHD_model.py", line 40, in initialize
    opt.n_blocks_local, opt.norm, gpu_ids=self.gpu_ids, opt=opt)
    File "D:\pythonProject\6_18\BringOldBack\Global\models\networks.py", line 60, in define_G
    netG = GlobalGenerator_v2(input_nc, output_nc, ngf, k_size, n_downsample_global, n_blocks_global,     norm_layer, opt=opt)
    NameError: name 'GlobalGenerator_v2' is not defined

could you please share with your idea ?I'm looking forward to you reply.thank you.

**Comment by Ssakura-go** [comment]
> > When I perform"python train_mapping.py --no_TTUR --NL_res --random_hole --use_SN --correlation_renormalize --training_dataset mapping --NL_use_mask --NL_fusion_method combine --non_local Setting_42 --use_v2_degradation --use_vae_which_epoch 200 --continue_train --name mapping_scratch --label_nc 0 --loadSize 256 --fineSize 256 --dataroot [your_data_folder] --no_instance --resize_or_crop crop_only --batchSize 36 --no_html --gpu_ids 0,1,2,3 --nThreads 8 --load_pretrainA [ckpt_of_domainA_SR_old_photos] --load_pretrainB [ckpt_of_domainB_old_photos] --l2_feat 60 --n_downsample_global 3 --mc 64 --k_size 4 --start_r 1 --mapping_n_block 6 --map_mc 512 --use_l1_feat --niter 150 --niter_decay 100 --outputs_dir [your_output_folder] --checkpoints_dir [your_ckpt_folder] --irregular_mask [absolute_path_of_mask_file]"
> > When I add the parameter'--irregular_mask' ,There was an error (UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 11: invalid start byte (my absolute path of mask file is ./mask/a.png ) and then there was another error: struct.error: unpack requires a buffer of 4 bytes
> 
> hello,when I'm going to train VAE_B with scratch , I don't find method, do you know how to train that ?thank you.I'm looking forward to your reply.

So do I.

**Comment by Pavan-207** [comment]
> When I perform"python train_mapping.py --no_TTUR --NL_res --random_hole --use_SN --correlation_renormalize --training_dataset mapping --NL_use_mask --NL_fusion_method combine --non_local Setting_42 --use_v2_degradation --use_vae_which_epoch 200 --continue_train --name mapping_scratch --label_nc 0 --loadSize 256 --fineSize 256 --dataroot [your_data_folder] --no_instance --resize_or_crop crop_only --batchSize 36 --no_html --gpu_ids 0,1,2,3 --nThreads 8 --load_pretrainA [ckpt_of_domainA_SR_old_photos] --load_pretrainB [ckpt_of_domainB_old_photos] --l2_feat 60 --n_downsample_global 3 --mc 64 --k_size 4 --start_r 1 --mapping_n_block 6 --map_mc 512 --use_l1_feat --niter 150 --niter_decay 100 --outputs_dir [your_output_folder] --checkpoints_dir [your_ckpt_folder] --irregular_mask [absolute_path_of_mask_file]"
> 
> When I add the parameter'--irregular_mask' ,There was an error (UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 11: invalid start byte (my absolute path of mask file is ./mask/a.png ) and then there was another error: struct.error: unpack requires a buffer of 4 bytes

did you find solution for this
