### ISSUE TITLE
can not save models for mapping_train

### ISSUE THREAD

**Issue by wanna69** [microsoft/Bringing-Old-Photos-Back-to-Life#233]
When I run train_mapping.py, the loss_log.txt and iter.txt are normal,but can not save models for mapping

**Comment by CodeMadUser** [comment]
hello,do you run train_domain_B.py? 
how do you solve the error?  could you share with me ? thank you .
Traceback (most recent call last):
  File "train_domain_B.py", line 48, in <module>
    model = create_model(opt)
  File "D:\pythonProject\6_18\BringOldBack\Global\models\models.py", line 17, in create_model
    model.initialize(opt)
  File "D:\pythonProject\6_18\BringOldBack\Global\models\pix2pixHD_model.py", line 40, in initialize
    opt.n_blocks_local, opt.norm, gpu_ids=self.gpu_ids, opt=opt)
  File "D:\pythonProject\6_18\BringOldBack\Global\models\networks.py", line 60, in define_G
    netG = GlobalGenerator_v2(input_nc, output_nc, ngf, k_size, n_downsample_global, n_blocks_global, norm_layer, opt=opt)
NameError: name 'GlobalGenerator_v2' is not defined

**Comment by CodeMadUser** [comment]
> When I run train_mapping.py, the loss_log.txt and iter.txt are normal,but can not save models for mapping

hello,do you run train_domain_B.py? 
how do you solve the error?  could you share with me ? thank you .
Traceback (most recent call last):
  File "train_domain_B.py", line 48, in <module>
    model = create_model(opt)
  File "D:\pythonProject\6_18\BringOldBack\Global\models\models.py", line 17, in create_model
    model.initialize(opt)
  File "D:\pythonProject\6_18\BringOldBack\Global\models\pix2pixHD_model.py", line 40, in initialize
    opt.n_blocks_local, opt.norm, gpu_ids=self.gpu_ids, opt=opt)
  File "D:\pythonProject\6_18\BringOldBack\Global\models\networks.py", line 60, in define_G
    netG = GlobalGenerator_v2(input_nc, output_nc, ngf, k_size, n_downsample_global, n_blocks_global, norm_layer, opt=opt)
NameError: name 'GlobalGenerator_v2' is not defined

**Comment by PhanThanhTrung** [comment]
@wanna69 I made a pull request to solve this problem in #232. I hope it would help.
