### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by whitenight1985** [microsoft/Bringing-Old-Photos-Back-to-Life#250]
![image](https://user-images.githubusercontent.com/109531969/205423946-5f444421-77e7-44b8-9784-eb7122d8da4f.png)
┌──(root㉿kali)-[/home/kirisawa/Bringing-Old-Photos-Back-to-Life]
└─# python3 run.py                     
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "/home/kirisawa/Bringing-Old-Photos-Back-to-Life/Global/test.py", line 6, in <module>
    from torch.autograd import Variable
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "/home/kirisawa/Bringing-Old-Photos-Back-to-Life/run.py", line 102, in <module>
    for x in os.listdir(stage_1_results):
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirisawa/Bringing-Old-Photos-Back-to-Life/output/stage_1_restore_output/restored_image'

I've run the requirements .txt but I'm still having problems.😭😭

**Comment by hanling1** [comment]
I met this problem too.
I tried  to re-install the torch by whl, but that not works.
Python 3.9

Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from torch.autograd import Variable
ImportError: No module named torch.autograd
Finish Stage 1 ...


Running Stage 2: Face Detection
Traceback (most recent call last):
  File "detect_all_dlib.py", line 4, in <module>
    import torch
ImportError: No module named torch
Finish Stage 2 ...

...

**Comment by zhangfeifei0907** [comment]
![image](https://user-images.githubusercontent.com/12770631/206965674-51f163e1-2cd4-4c4a-8a85-17f18c054c55.png)

**Comment by gyh-1** [comment]
Have you solved the problem？ I met the same one.

**Comment by boonyachengdu** [comment]
root@master:/usr/local/ai/Bringing-Old-Photos-Back-to-Life# pip install -r requirements.txt
Collecting torch
Killed
root@master:/usr/local/ai/Bringing-Old-Photos-Back-to-Life# 
=======================================================

root@master:/usr/local/ai/Bringing-Old-Photos-Back-to-Life# python run.py --input_folder /usr/local/ai/Bringing-Old-Photos-Back-to-Life/input_folder    --output_folder /usr/local/ai/Bringing-Old-Photos-Back-to-Life/output_folder  --GPU 0
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from torch.autograd import Variable
ModuleNotFoundError: No module named 'torch'
Finish Stage 1 ...


Running Stage 2: Face Detection
Traceback (most recent call last):
  File "detect_all_dlib.py", line 4, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Finish Stage 2 ...


Running Stage 3: Face Enhancement
Traceback (most recent call last):
  File "test_face.py", line 7, in <module>
    import data
  File "/usr/local/ai/Bringing-Old-Photos-Back-to-Life/Face_Enhancement/data/__init__.py", line 5, in <module>
    import torch.utils.data
ModuleNotFoundError: No module named 'torch'
Finish Stage 3 ...


Running Stage 4: Blending
Traceback (most recent call last):
  File "align_warp_back_multiple_dlib.py", line 4, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Finish Stage 4 ...


All the processing is done. Please check the results.
root@master:/usr/local/ai/Bringing-Old-Photos-Back-to-Life#

**Comment by digvijayu** [comment]
Having the same problem any ideas how to fix this, tried installing torch several times but no use
with `pip list` I can see its installed

<img width="400" alt="image" src="https://user-images.githubusercontent.com/7867644/235837103-5876a499-07ce-42f8-95ba-6d7f7f57477e.png">

**Comment by ChitturiSaiSuman** [comment]
Changing `python` in [line #55 in the run.py](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/blob/33875eccf4ebcd3665cf38cc56f3a0ce563d3a9c/run.py#L55) to `python3` worked for me. But, sadly I don't have an NVIDIA GPU in my Laptop.
