### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mortaza01** [microsoft/Bringing-Old-Photos-Back-to-Life#257]
All the processing is done. Please check the results.
Traceback (most recent call last):
File "/root/.pyenv/versions/3.8.14/lib/python3.8/site-packages/cog/server/worker.py", line 214, in _predict
result = self._predictor.predict(**payload)
File "predict.py", line 177, in predict
final_output = os.listdir(os.path.join(self.output_folder, "final_output"))[0]
IndexError: list index out of range

**Comment by sexyprofessor** [comment]
index out of bound. Check the condition. Its a small issue mostly regarding base case conditions
