### ISSUE TITLE
What happened? I ran it again but the result is not correct?

### ISSUE THREAD

**Issue by hktalent** [microsoft/Bringing-Old-Photos-Back-to-Life#266]
not ok

**Comment by hktalent** [comment]
```
 https://facevc.blob.core.windows.net/zhanbo/old_photo/pretrain/Global/checkpoints.zip
Resolving facevc.blob.core.windows.net (facevc.blob.core.windows.net)... 52.239.237.4
Connecting to facevc.blob.core.windows.net (facevc.blob.core.windows.net)|52.239.237.4|:443... connected.
HTTP request sent, awaiting response... 404 The specified resource does not exist.
2023-03-22 12:47:29 ERROR 404: The specified resource does not exist..

unzip:  cannot find or open checkpoints.zip, checkpoints.zip.zip or checkpoints.zip.ZIP.
/content/photo_restoration
```

**Comment by hktalent** [comment]
### 5 Restore photos (normal mode)
```
Running Stage 4: Blending
Warning: There is no face in e.png
Warning: There is no face in d.png
Traceback (most recent call last):
  File "/content/photo_restoration/Face_Detection/align_warp_back_multiple_dlib.py", line 428, in <module>
    blended = blur_blending_cv2(warped_back, blended, backward_mask)
  File "/content/photo_restoration/Face_Detection/align_warp_back_multiple_dlib.py", line 219, in blur_blending_cv2
    mask *= 255.0
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
Finish Stage 4 ...

```
### 8 Restore the photos with scratches
```

Running Stage 4: Blending
Traceback (most recent call last):
  File "/content/photo_restoration/Face_Detection/align_warp_back_multiple_dlib.py", line 428, in <module>
    blended = blur_blending_cv2(warped_back, blended, backward_mask)
  File "/content/photo_restoration/Face_Detection/align_warp_back_multiple_dlib.py", line 219, in blur_blending_cv2
    mask *= 255.0
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
Finish Stage 4 ...

```

**Comment by hktalent** [comment]
### image_restore = PIL.Image.open(os.path.join(output_path, 'final_output', filename))
```
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-9-3121ae23a960>](https://qco15ajxmyl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230320-060136-RC00_517924595#) in <module>
     10     print(filename)
     11     image_original = PIL.Image.open(os.path.join(input_path, filename))
---> 12     image_restore = PIL.Image.open(os.path.join(output_path, 'final_output', filename))
     13 
     14     display(make_grid(image_original, image_restore))

[/usr/local/lib/python3.9/dist-packages/PIL/Image.py](https://qco15ajxmyl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230320-060136-RC00_517924595#) in open(fp, mode, formats)
   2973 
   2974     if filename:
-> 2975         fp = builtins.open(filename, "rb")
   2976         exclusive_fp = True
   2977 

FileNotFoundError: [Errno 2] No such file or directory: '/content/photo_restoration/output/final_output/a.png'
```

**Comment by hktalent** [comment]
<img width="863" alt="image" src="https://user-images.githubusercontent.com/18223385/226968258-38086f9f-5226-49dc-b2d3-56cc34ae7a62.png">

**Comment by hktalent** [comment]
if input file 
2.6M
3024 × 3024

now Error:
```
Skip a.png due to an error:
CUDA out of memory. Tried to allocate 1216.88 GiB (GPU 0; 14.75 GiB total capacity; 4.83 GiB already allocated; 6.29 GiB free; 7.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```
AI answer
```
这个错误说明您的CUDA内存不足以分配所需的张量（tensor），因此您需要采取一些措施来解决它。以下是一些可能有帮助的解决方法：

1. 减少batch size（每次处理的数据量），这是最常用的方法之一，可以尝试减小batch size的值。
2. 减少模型的大小或复杂度。可以尝试使用更小的模型或者更少的层数来解决此类问题。
3. 检查是否有无效的张量在使用中，这些张量可能会导致内存泄漏。在每个batch处理结束后，应该将不再使用的张量从GPU中释放。
4. 尝试使用PyTorch的调用 max_split_size_mb，这可能有助于避免碎片化导致的内存分配问题。
5. 如果您有多个GPU，可以尝试使用分布式训练，这将允许您使用多个GPU并最大限度地减少内存使用。
6. 如果您的计算机上有足够的RAM，您可以尝试增加swap memory。虽然这不是最佳解决方案，但它可以提供一些帮助。

这是一些可能有用的方法。每个问题都不同，效果因人而异，请根据具体情况选择最适合您的方法。
```

**Comment by hktalent** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/18223385/226975806-c4d4e870-6e0c-4937-8036-4eb61f80ba18.png">

**Comment by hktalent** [comment]
I don't know why  “no face in a.png”
```
apping: You are using multi-scale patch attention, conv combine + mask input
Now you are processing a.png
Now you are processing b.png
Now you are processing c.png
Now you are processing d.png
Now you are processing e.png
Finish Stage 1 ...


Running Stage 2: Face Detection
1
2
Warning: There is no face in a.png
1
1
Finish Stage 2 ...


Running Stage 3: Face Enhancement
```
<img width="721" alt="image" src="https://user-images.githubusercontent.com/18223385/226975806-c4d4e870-6e0c-4937-8036-4eb61f80ba18.png">
