### ISSUE TITLE
Not working (conda with env)

### ISSUE THREAD

**Issue by Arifi** [microsoft/Bringing-Old-Photos-Back-to-Life#278]
Hi,

I've issue which i don't understand, I fellowed all steps but can't run or get any results, any help please ? here the output

```
Running Stage 1: Overall restoration
initializing the dataloader
model weights loaded
Traceback (most recent call last):
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Global\detection.py", line 178, in <module>
    main(config)
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Global\detection.py", line 97, in main
    model.to(config.GPU)
  File "C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Global\test.py", line 97, in <module>
    opt = TestOptions().parse(save=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Global\options\base_options.py", line 354, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\torch\cuda\__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
Finish Stage 1 ...


Running Stage 2: Face Detection
C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Finish Stage 2 ...


Running Stage 3: Face Enhancement
The main GPU is
0
Traceback (most recent call last):
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Face_Enhancement\test_face.py", line 15, in <module>
    opt = TestOptions().parse()
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Face_Enhancement\options\base_options.py", line 287, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\torch\cuda\__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
Finish Stage 3 ...


Running Stage 4: Blending
C:\Users\Mourad\anaconda3\envs\gan3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Finish Stage 4 ...


All the processing is done. Please check the results.
```

**Comment by anudeepadi** [comment]
Hey @Arifi,

Based on the output: Your PyTorch isn't talking to CUDA. Make sure your GPU's CUDA-compatible, then reinstall PyTorch with CUDA enabled.
_cuda_setDevice Error: Sort out this issue, and it will likely go away.

**Comment by Arifi** [comment]
Hey @anudeepadi , thanks for response, I thought this repo was dead...
My GPU is CUDA compatible and I fellowed all steps, can you tell me how I can reinstall PyTorch with CUDA enabled ? I'm asking because all my tries did nothing..

I've ComfyUI working well, also tested GFPGAN which has same issue, but when I run it under conda consol it works fine, but this one no. any help ?

**Comment by Arifi** [comment]
0Hi @anudeepadi , maybe this could help :

```
(base) C:\Users\Mourad>python -c "import torch; print(torch.cuda.device_count())"
0

(base) C:\Users\Mourad>python -c "import torch; print(torch.rand(2,3).cuda())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Mourad\anaconda3\Lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(base) C:\Users\Mourad>
```

**Comment by Arifi** [comment]
Also :

```
(base) C:\Users\Mourad>nvidia-smi
Wed Aug 30 14:30:38 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.67                 Driver Version: 536.67       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  | 00000000:0C:00.0  On |                  N/A |
|  0%   52C    P8              10W / 170W |    679MiB / 12288MiB |      6%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by Arifi** [comment]
Hi,

Ths commande solved my issue, instead of the default one:
`pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121`
