### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Arifi** [microsoft/Bringing-Old-Photos-Back-to-Life#279]
Can someone help please ? I fellowed all steps but nothing is working
Here the output: 

```
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Global\detection.py", line 12, in <module>
    import torch
  File "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
Traceback (most recent call last):
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Global\test.py", line 6, in <module>
    from torch.autograd import Variable
  File "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
Finish Stage 1 ...


Running Stage 2: Face Detection
Traceback (most recent call last):
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Face_Detection\detect_all_dlib.py", line 4, in <module>
    import torch
  File "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
Finish Stage 2 ...


Running Stage 3: Face Enhancement
Traceback (most recent call last):
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Face_Enhancement\test_face.py", line 7, in <module>
    import data
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Face_Enhancement\data\__init__.py", line 5, in <module>
    import torch.utils.data
  File "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
Finish Stage 3 ...


Running Stage 4: Blending
Traceback (most recent call last):
  File "C:\BOPTL\Bringing-Old-Photos-Back-to-Life\Face_Detection\align_warp_back_multiple_dlib.py", line 4, in <module>
    import torch
  File "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\Users\Mourad\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
Finish Stage 4 ...


All the processing is done. Please check the results.
```

**Comment by lightshadown** [comment]
Its only telling you that it cant find the necesary module in this case pytorch, are you sure you installed pytorch? run the list command under pip and search for pytorch ,try usign the colab version and see if theres any diference

**Comment by jolzi** [comment]
It could be that your installed CUDA version and your installed Python version made the torch installation fail. If you used the (very old) python version 3.6 like recommended in the repository and installed a new CUDA version, installing torch will fail because it can not bridge this gap. I recommend using CUDA 11.8 and Python 3.8
