### ISSUE TITLE
IndexError: list index out of range (model on replicate.com)

### ISSUE THREAD

**Issue by OmlineEditor** [microsoft/Bringing-Old-Photos-Back-to-Life#290]
I can't process the photo on the website at https://replicate.com/microsoft/bringing-old-photos-back-to-life
I changed the size of the photo to the minimum possible, it is 800x900 pixels in size, it cannot be smaller. but the processing is not happening, there is an error. please fix it and upload the new version to the website replicate.com 
```
/src
Running Stage 1: Overall restoration
detection.py:25: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
def data_transforms(img, full_size, method=Image.BICUBIC):
initializing the dataloader
model weights loaded
directory of testing image: /src/input/cog_temp
processing tmpzqazegs5in_resize_for_replicate900.JPG
test.py:18: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
def data_transforms(img, method=Image.BILINEAR, scale=False):
You are using NL + Res
Now you are processing tmpzqazegs5in_resize_for_replicate900.png
Skip tmpzqazegs5in_resize_for_replicate900.png due to an error:
CUDA out of memory. Tried to allocate 7.78 GiB (GPU 0; 14.58 GiB total capacity; 8.35 GiB already allocated; 479.56 MiB free; 12.93 GiB reserved in total by PyTorch)
Finish Stage 1 ...
Running Stage 2: Face Detection
Finish Stage 2 ...
Running Stage 3: Face Enhancement
The main GPU is
0
dataset [FaceTestDataset] of size 0 was created
The size of the latent vector size is [16,16]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
hi :)
Finish Stage 3 ...
Running Stage 4: Blending
Finish Stage 4 ...
All the processing is done. Please check the results.
Traceback (most recent call last):
File "/root/.pyenv/versions/3.8.14/lib/python3.8/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "predict.py", line 177, in predict
final_output = os.listdir(os.path.join(self.output_folder, "final_output"))[0]
IndexError: list index out of range
```

**Comment by Arjunjathap04** [comment]
![Uploading IMG_20240226_203815_9x16.jpg…]()

**Comment by OmlineEditor** [comment]
I didn't understand what you said to me.
