### ISSUE TITLE
"Restore the photos with scratches" section fails with **"FileNotFoundError: [Errno 2] No such file or directory: '/content/photo_restoration/Global/checkpoints/detection/FT_Epoch_latest.pt'"**

### ISSUE THREAD

**Issue by jareilly** [microsoft/Bringing-Old-Photos-Back-to-Life#295]
I am trying to run on Google Colab, using a Connected T4 hosted runtime.

The "Restore the photos with scratches" section fails with **"FileNotFoundError: [Errno 2] No such file or directory: '/content/photo_restoration/Global/checkpoints/detection/FT_Epoch_latest.pt'"**

1) Colab runs this:
!rm -rf /content/photo_restoration/output/*
!python run.py --input_folder /content/photo_restoration/test_images/old_w_scratch/ --output_folder /content/photo_restoration/output/ --GPU 0 --with_scratch

2) Output is this:
Running Stage 1: Overall restoration
initializing the dataloader
Traceback (most recent call last):
  File "/content/photo_restoration/Global/detection.py", line 178, in <module>
    main(config)
  File "/content/photo_restoration/Global/detection.py", line 92, in main
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/content/photo_restoration/Global/checkpoints/detection/FT_Epoch_latest.pt'
You are using NL + Res
./checkpoints/restoration/VAE_A_quality/latest_net_G.pth not exists yet!
./checkpoints/restoration/VAE_B_scratch/latest_net_G.pth not exists yet!
./checkpoints/restoration/mapping_scratch/latest_net_mapping_net.pth not exists yet!
Traceback (most recent call last):
  File "/content/photo_restoration/Global/test.py", line 114, in <module>
    input_loader = os.listdir(opt.test_input)
FileNotFoundError: [Errno 2] No such file or directory: '/content/photo_restoration/output/stage_1_restore_output/masks/input'

**Comment by Xadoy** [comment]
It's likely caused by the same issue of #252

**Comment by zpskt** [comment]
plase check README.md. please ensure u executed 'wget https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/releases/download/v1.0/global_checkpoints.zip' and put it in right floder 

![Image](https://github.com/user-attachments/assets/18c911b2-3a1b-4d2b-846d-7d6e50c8cbae)

**Comment by Senci83** [comment]
> plase check README.md. please ensure u executed 'wget https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/releases/download/v1.0/global_checkpoints.zip' and put it in right floder
> 
> ![Image](https://github.com/user-attachments/assets/18c911b2-3a1b-4d2b-846d-7d6e50c8cbae)

Hi 

i was hoping if you could also help me with an Prompt execution failed
Prompt outputs failed validation im getting when trying to run Old-Photos-Back-to-Life workflow.

This is the error im getting. 
I have all the files in the right folders and sub folders. But i cant get past this error. PLS help :)
<img width="1466" height="978" alt="Image" src="https://github.com/user-attachments/assets/7bee880c-69fa-4adc-bb79-278793c03219" />

Best regards 

SB.
