### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by akenateb** [microsoft/Bringing-Old-Photos-Back-to-Life#32]
I have found this error when I try:
python run.py --input_folder /home/akenateb/Bringing-Old-Photos-Back-to-Life/imgs/ --output_folder /home/akenateb/Bringing-Old-Photos-Back-to-Life/imgs/output/ --GPU 0

`Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    opt = TestOptions().parse(save=False)
  File "/root/photos/Bringing-Old-Photos-Back-to-Life/Global/options/base_options.py", line 350, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/root/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 263, in set_device
    torch._C._cuda_setDevice(device)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
`

nvcc --version: vcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

Any help?
Thanks in advance

**Comment by zhangmozhe** [comment]
you can try to run with --GPU -1
