### ISSUE TITLE
Unknown CUDA error although everything is set up properly

### ISSUE THREAD

**Issue by thistehneisen** [microsoft/Bringing-Old-Photos-Back-to-Life#52]
```
┌─[root@null]─[/home/null/Code/Python/Bringing-Old-Photos-Back-to-Life]
└──╼ #CUDA_VISIBLE_DEVICES=0 python run.py --input_folder /home/null/Desktop/test/ --output_folder /home/seq/Desktop/test_re/ --GPU 0
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    opt = TestOptions().parse(save=False)
  File "/home/null/Code/Python/Bringing-Old-Photos-Back-to-Life/Global/options/base_options.py", line 350, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 263, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
Traceback (most recent call last):
  File "run.py", line 91, in <module>
    for x in os.listdir(stage_1_results):
FileNotFoundError: [Errno 2] No such file or directory: '/home/null/Desktop/test_re/stage_1_restore_output/restored_image'
┌─[✗]─[root@null]─[/home/null/Code/Python/Bringing-Old-Photos-Back-to-Life]
└──╼ #nvidia-smi
Sun Nov 22 15:45:53 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    On   | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8     2W /  N/A |      6MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1207      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

Has anyone else experienced this? Any suggestions for a solution here?

**Comment by thistehneisen** [comment]
Even after making modifications so that Xorg doesn't use the Nvidia graphics card, having the same issue.
```
┌─[root@null]─[/home/null]
└──╼ #nvidia-smi
Sun Nov 22 15:59:56 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    On   | 00000000:01:00.0 Off |                  N/A |
| N/A   54C    P8     2W /  N/A |      1MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by zhangmozhe** [comment]
Will you run the project again. We recently made a fix for that.

**Comment by thistehneisen** [comment]
Just retried with the modifications pulled at `run.py`

```┌─[✗]─[root@null]─[/home/seq/Code/Python/Bringing-Old-Photos-Back-to-Life]
└──╼ #CUDA_VISIBLE_DEVICES=0 python run.py --input_folder /home/seq/Desktop/Latvija/ --output_folder /home/seq/Desktop/Latvija_re/ --GPU 0
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    opt = TestOptions().parse(save=False)
  File "/home/seq/Code/Python/Bringing-Old-Photos-Back-to-Life/Global/options/base_options.py", line 350, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 263, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
Traceback (most recent call last):
  File "run.py", line 95, in <module>
    for x in os.listdir(stage_1_results):
FileNotFoundError: [Errno 2] No such file or directory: '/home/seq/Desktop/Latvija_re/stage_1_restore_output/restored_image'```

**Comment by zhangmozhe** [comment]
You can manually create the output directory if the code fails to create it.
