### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy' ！  Installation problem！

### ISSUE THREAD

**Issue by xuejingtai** [microsoft/Bringing-Old-Photos-Back-to-Life#65]
pip install -r requirements.txt
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Collecting torchvision
  Using cached torchvision-0.2.2.post3-py2.py3-none-any.whl (64 kB)
Collecting dlib
  Using cached dlib-19.21.0.tar.gz (3.2 MB)
Collecting scikit-image
  Using cached scikit-image-0.17.2.tar.gz (29.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\国b的小仓库\appdata\local\programs\python\python39-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\国b的小仓库\\AppData\\Local\\Temp\\pip-install-wvym9snv\\scikit-image\\setup.py'"'"'; __file__='"'"'C:\\Users\\国b的小仓库\\AppData\\Local\\Temp\\pip-install-wvym9snv\\scikit-image\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\国b的小仓库\AppData\Local\Temp\pip-pip-egg-info-4a7567v8'
         cwd: C:\Users\国b的小仓库\AppData\Local\Temp\pip-install-wvym9snv\scikit-image\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\国b的小仓库\AppData\Local\Temp\pip-install-wvym9snv\scikit-image\setup.py", line 234, in <module>
        'build_ext': openmp_build_ext(),
      File "C:\Users\国b的小仓库\AppData\Local\Temp\pip-install-wvym9snv\scikit-image\setup.py", line 58, in openmp_build_ext
        from numpy.distutils.command.build_ext import build_ext
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

When I enter pip install -r requirements.txt in my powershell, an error is reported 。Thank you all！

**Comment by xuejingtai** [comment]
![Uploading image.png…]()

**Comment by xuejingtai** [comment]
![image](https://user-images.githubusercontent.com/48974600/100533820-92155000-3243-11eb-808e-8939eff6df1f.png)
