### ISSUE TITLE
Colab example with --with_scratch gives error

### ISSUE THREAD

**Issue by Artyrm** [microsoft/Bringing-Old-Photos-Back-to-Life#67]
`RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
You are using NL + Res`

What can be done about it?

**Comment by zelenooki87** [comment]
same error happens here
`Traceback (most recent call last):
  File "detection.py", line 156, in <module>
    main(config)
  File "detection.py", line 128, in main
    P = torch.sigmoid(model(scratch_image))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/photo_restoration/Global/detection_models/networks.py", line 110, in forward
    x = self.first(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same`

**Comment by zhangmozhe** [comment]
Hi, thanks for your feedback. We've just fixed the update and it works now. Please have a try again.
