### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/jingliao'

### ISSUE THREAD

**Issue by bwanaaa** [microsoft/Bringing-Old-Photos-Back-to-Life#88]
using an image named 2.jpg in the base directory(Bringing-Old-Photos-Back-to-Life), the command

`python run.py --input_folder ./2.jpg `
or
`python run.py --input_folder /2.jpg `

gives

```
Traceback (most recent call last):
  File "/home/stefan/photoRestoration/Bringing-Old-Photos-Back-to-Life/run.py", line 40, in <module>
    os.makedirs(opts.output_folder)
  File "/home/stefan/miniconda3/envs/photoRest/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/stefan/miniconda3/envs/photoRest/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/stefan/miniconda3/envs/photoRest/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/home/stefan/miniconda3/envs/photoRest/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jingliao'

```

**Comment by bwanaaa** [comment]
FIXED by changing line 23 in run.py

**Comment by mohameed7841987** [comment]
****
